// Generated by CoffeeScript 1.6.2
var getStartOfOccupation, occupationsPerHour;

occupationsPerHour = function(floor, room) {
  var d;

  d = new Date();
  return {
    floor: floor,
    room: room,
    year: d.getUTCFullYear(),
    month: d.getUTCMonth(),
    day: d.getUTCDate(),
    hour: d.getUTCHours()
  };
};

getStartOfOccupation = function(event, Event, callback) {
  return Event.findOne({
    'floor': event.floor,
    'room': event.room,
    'status': 1
  }, {}, {
    sort: {
      'time': -1
    }
  }).exec(function(err, event) {
    if (err != null) {
      return false;
    }
    return callback(event.time);
  });
};

exports.logEvent = function(event, req, res, Event, FloorStats) {
  event.save(function(err) {
    if (err != null) {
      res.statusCode = 400;
      return res.send("Error");
    } else {
      res.statusCode = 200;
      return res.send(event);
    }
  });
  if (parseInt(event.status) === 1) {
    return FloorStats.update(occupationsPerHour(event.floor, event.room), {
      $inc: {
        occupation: 1
      }
    }, {
      upsert: true
    }, function(err) {});
  } else {
    return getStartOfOccupation(event, Event, function(response) {
      var diff, endOfOccupation, startOfOccupation;

      endOfOccupation = event.time;
      startOfOccupation = response;
      diff = new Date(endOfOccupation - startOfOccupation).getTime();
      return FloorStats.update(occupationsPerHour(event.floor, event.room), {
        $inc: {
          duration: diff
        }
      }, {
        upsert: true
      }, function(err) {});
    });
  }
};
