default:
	echo "Please install CocoaPods: gem install cocoapods"
	echo "Please install dependencies from this directory: pod install"
	xcodebuild -workspace GottaGo.xcworkspace -scheme GottaGo -configuration Release clean build
	open build