// Generated by CoffeeScript 1.6.2
var config, crypto, defineModels;

crypto = require('crypto');

config = require('../config');

defineModels = function(mongoose, fn) {
  var Event, ObjectId, Que, Schema;

  Schema = mongoose.Schema;
  ObjectId = Schema.ObjectId;
  Event = new Schema({
    'floor': Number,
    'room': String,
    'time': {
      type: Date,
      "default": Date.now
    },
    'status': Number
  }, {
    toObject: {
      virtuals: true
    },
    toJSON: {
      virtuals: true
    }
  });
  Event.virtual('name').get(function() {
    return 'config.room.names[this.floor + this.room]';
  });
  return Que = new Schema({
    'floor': Number,
    'contact': String,
    'time': {
      type: Date,
      "default": Date.now
    },
    'status': Number
  });
};

mongoose.model('Event', Event);

mongoose.model('Que', Que);

fn();

exports.defineModels = defineModels;
