// Generated by CoffeeScript 1.6.2
var crypto, defineModels;

crypto = require('crypto');

defineModels = function(mongoose, fn) {
  var Event, ObjectId, Schema;

  Schema = mongoose.Schema;
  ObjectId = Schema.ObjectId;
  Event = new Schema({
    'floor': Number,
    'room': String,
    'time': {
      type: Date,
      "default": Date.now
    },
    'status': String
  });
  mongoose.model('Event', Event);
  return fn();
};

exports.defineModels = defineModels;
